version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: multi-tenant-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: multi_tenant_admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - multi-tenant-network

  redis:
    image: redis:7.0-alpine
    container_name: multi-tenant-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - multi-tenant-network

volumes:
  mysql_data:
  redis_data:

networks:
  multi-tenant-network:
    driver: bridge