// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"project_temp/service/order/cmd/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Cros, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/order/get/:id",
					Handler: getOrderHandler(serverCtx),
				},
			}...,
		),
	)
}
